### PR TITLE
Use Dependabot to keep dependencies up to date, and update winit to 0.25

### PR DESCRIPTION
**Pull request by SonnyX**

### CODE REVIEW

**Comment by pravic** [comment]
I don't want to use dependabot. It's too annoying, it creates a PR for every minor update (which results in basically spamming) and it forces you to constantly manage the dependencies. But what's the point? 

I know, some people think that if a project isn't constantly being updated, it's dead. Well, it's their problem - for me, as long as it does the job and isn't broken, I am totally fine with its age. For me, a more serious problem is when you create an issue but the author is not responding or ignores it. 

I don't want to keep up with `winit` - it changes [too often](https://github.com/sciter-sdk/rust-sciter/commits/master/.travis.yml) (see, how many times I had to bump the MSRV because of it)  and too often it breaks something. Since I use it only for an example, I am totally fine with sticking to some old version - as long as the example compiles.

And now I realized that I forgot to push a PR that converts `windowless` to a separate crate with its own dependencies - which would isolate `winit`.

**Comment by SonnyX** [comment]
Fair enough, thanks for the explanation!
Also I am fully aware this project is far from dead, thanks for doing a great job maintaining it!

The only reason why I submit dependency PR's to packages is to prevent cargo from having many different versions of the same package resulting in way bigger final compilation sizes!

Thanks for the quick response & handling of the PR.

**Comment by pravic** [comment]
> to prevent cargo from having many different versions

Yeah, that is something I don't like either. Do you use winit in your project?

**Comment by pravic** [comment]
Also, see #112 - `winit` now in its own crate, so it won't be compiled by default. So, we are back to only two dependencies.

**Comment by pravic** [comment]
Well, with #112 it is even no longer an issue. Thanks!

**Pull request closed without merging**
