### PR TITLE
Enable debug mode for example "minimal"

### PR DESCRIPTION
**Pull request by baijifeilong**
Debug mode is required to connect to the inspector.

### CODE REVIEW

**Comment by pravic** [comment]
It is enabled by default. Isn't it?

https://github.com/sciter-sdk/rust-sciter/blob/master/src/host.rs#L189..L190

**Comment by 7sDream** [comment]
@pravic 

But it seems isn't enabled when I try the minimal example.

I need add the line in this PR to use the inspector.

My env: 
- OS: macOS 10.14
- Sciter SDK: 4.2.6.10
- Sciter Rust: master branch

**Comment by pravic** [comment]
Interesting. I need to check it again then.

**Comment by pravic** [comment]
A reminder for me.

**Comment by pravic** [comment]
Right, global debug mode doesn't work on OSX (https://sciter.com/forums/topic/global-sciter_set_debug_mode-does-not-work-in-osx/).

We'll see about the correct way to do it.

**Comment by pravic** [comment]
Another reminder to look on window creation under OSX.

**Comment by pravic** [comment]
Apparently, it was fixed in 4.4.2.7. 

Just checked on a recent SDK, works well.

**Pull request closed without merging**
